# Generated by Django 4.2.3 on 2023-07-31 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoparkmodel',
            options={'ordering': ('id',)},
        ),
    ]
