# Generated by Django 4.2.4 on 2023-08-07 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usermodel_options_alter_profilemodel_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=(?:.*[`~!@#$%^&*()\\-_+=\\\\\\|\\\'\\"\\;\\:\\/?.>,<\\[\\]\\{\\}]){2,})[a-zA-Z\\d`~!@#$%^&*()\\-_+=\\\\\\|\\\'\\"\\;\\:\\/?.>,<\\[\\]\\{\\}]{8,30}$', ['min 1 lowercase', 'min 1 uppercase', 'min 2 digits', 'min 1 special character', 'length 8-30 characters'])]),
        ),
    ]
